name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_14.2.app

    - name: Build and Test
      run: |
        xcodebuild clean test \
        -project DevFest.xcodeproj \
        -scheme DevFest \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
        ONLY_ACTIVE_ARCH=YES
